language: scala
scala:
  - 2.12.4-bin-typelevel-4
jdk:
  - oraclejdk8

# From http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
# Use container-based infrastructure
sudo: false
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
