[project]
scalaVersion      = "2.12.4-bin-typelevel-4"
scalaOptions      = ["-Yliteral-types"]
scalaOrganisation = "org.typelevel"
testFrameworks    = ["org.scalatest.tools.Framework"]

[module.leaf]
root      = "."
targets   = ["jvm"]
scalaDeps = [
  ["io.circe", "circe-core"   , "0.11.1"],
  ["io.circe", "circe-generic", "0.11.1"],
  ["io.circe", "circe-parser" , "0.11.1"]
]

[module.leaf-core.jvm]
moduleDeps = ["leaf", "leaf-notebook"]
root       = "core"
sources    = ["core/src/main/scala"]
scalaDeps  = [
  ["tech.sparse"  , "pine"     , "0.1.5"],
  ["org.scalameta", "fastparse", "1.0.1"]
]
javaDeps = [
  ["com.vladsch.flexmark", "flexmark"              , "0.50.18"],
  ["com.vladsch.flexmark", "flexmark-ext-tables"   , "0.50.18"],
  ["com.vladsch.flexmark", "flexmark-ext-footnotes", "0.50.18"]
]

[module.leaf-core.test.jvm]
sources   = ["core/src/test/scala"]
scalaDeps = [
  ["org.scalatest" , "scalatest" , "3.0.8"]
]

[module.leaf-notebook.jvm]
moduleDeps = ["leaf"]
root       = "notebook"
sources    = ["notebook/src/main/scala"]
scalaDeps  = [
  ["com.lihaoyi", "sourcecode", "0.1.7"]
]
